# cleans $(Agent.BuildDirectory) unconditionally on multiple platforms

steps:
- script: rd /S /Q $(Agent.BuildDirectory)
  displayName: Clean build files (Windows)
  condition: eq(variables['Agent.OS'], 'Windows_NT') # and always()
- script: rm -rf $(Agent.BuildDirectory)
  displayName: Clean build files (POSIX)
  condition: not(eq(variables['Agent.OS'], 'Windows_NT')) # and always()
  continueOnError: true  # continuing on error for this step, since linux build folder is somehow getting permission issue
