# sets Python manylinux variables
# the Python version is specified with the PythonVersion variable

steps:
- task: PythonScript@0
  displayName: 'Set Python manylinux variables'
  inputs:
    pythonInterpreter: /usr/bin/python3
    scriptSource: inline
    script: |
      version = "$(PythonVersion)"

      if version == "3.8":
        variables = {
          "PythonManylinuxDir": "/opt/python/cp38-cp38",
          "PythonManylinuxIncludeDir": "/opt/python/cp38-cp38/include/python3.8",
        }
      elif version == "3.9":
        variables = {
          "PythonManylinuxDir": "/opt/python/cp39-cp39",
          "PythonManylinuxIncludeDir": "/opt/python/cp39-cp39/include/python3.9",
        }
      elif version == "3.10":
        variables = {
          "PythonManylinuxDir": "/opt/python/cp310-cp310",
          "PythonManylinuxIncludeDir": "/opt/python/cp310-cp310/include/python3.10",
        }
      elif version == "3.11":
        variables = {
          "PythonManylinuxDir": "/opt/python/cp311-cp311",
          "PythonManylinuxIncludeDir": "/opt/python/cp311-cp311/include/python3.11",
        }
      else:
        raise ValueError("Unsupported Python version: '{}'".format(version))

      for name, value in variables.items():
        print("Setting variable: {} = '{}'".format(name, value))
        print("##vso[task.setvariable variable={}]{}".format(name, value))
