stages:
- stage: Python_Packaging

  jobs:
    - job: Linux_py_GPU_Wheels
      timeoutInMinutes: 180
      workspace:
        clean: all
      pool: Onnxruntime-Linux-GPU
      strategy:
        matrix:
          # TODO: Readd these two nightly pipelines after finding a solution that works for
          # both torch stable and torch nightly when torch API changes.
          # Python38 TorchAndOrtNightly Cuda10.2:
          #   PythonVersion: '3.8'
          #   PublicDockerFile: 'docker/Dockerfile.ort-torch-and-onnxruntime-nightly-cu102-cudnn7-devel-ubuntu18.04'
          # Python38 TorchAndOrtNightly Cuda11.1:
          #   PythonVersion: '3.8'
          #   PublicDockerFile: 'docker/Dockerfile.ort-torch-and-onnxruntime-nightly-cu111-cudnn8-devel-ubuntu18.04'
          Python38 Torch181 onnxruntimeNightly Cuda10.2:
            PythonVersion: '3.8'
            PublicDockerFile: 'docker/Dockerfile.ort-torch181-onnxruntime-nightly-cu102-cudnn7-devel-ubuntu18.04'
          Python38 Torch181 onnxruntimeNightly Cuda11.1:
            PythonVersion: '3.8'
            PublicDockerFile: 'docker/Dockerfile.ort-torch181-onnxruntime-nightly-cu111-cudnn8-devel-ubuntu18.04'
          Python38 Torch190 onnxruntimeNightly Cuda10.2:
            PythonVersion: '3.8'
            PublicDockerFile: 'docker/Dockerfile.ort-torch190-onnxruntime-nightly-cu102-cudnn7-devel-ubuntu18.04'
          Python38 Torch190 onnxruntimeNightly Cuda11.1:
            PythonVersion: '3.8'
            PublicDockerFile: 'docker/Dockerfile.ort-torch190-onnxruntime-nightly-cu111-cudnn8-devel-ubuntu18.04'
            UploadWheel: 'yes'

      variables:
        BuildType: 'nightly'

      steps:
      - checkout: self
        clean: true
        submodules: recursive

      - template: templates/packaging-pipeline-steps.yml
        parameters:
          PythonVersion: $(PythonVersion)
          PublicDockerFile: $(PublicDockerFile)
          UploadWheel: $(UploadWheel)
          BuildType: $(BuildType)

      - template: templates/component-governance-component-detection-steps.yml
        parameters:
          condition: 'succeeded'

      - template: templates/clean-agent-build-directory-step.yml
