# ONNX Runtime Training Module for PyTorch
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# CUDA development image for building sources
FROM nvidia/cuda:11.6.2-cudnn8-devel-ubuntu18.04 as builder
ARG TORCH_CUDA_VERSION=cu116
ARG ONNXRUNTIME_TRAINING_VERSION=1.12.0
ARG TORCH_VERSION=1.12.1
ARG TORCHVISION_VERSION=0.13.1

# Install and update tools to minimize security vulnerabilities
RUN apt-get update
RUN apt-get install -y software-properties-common wget apt-utils patchelf git libprotobuf-dev protobuf-compiler cmake
RUN unattended-upgrade
RUN apt-get autoremove -y

# Add repository to install python 3.9
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt update
RUN apt install python3.9

# Python and pip
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN apt-get install -y python3-pip
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
RUN pip install --upgrade pip

# PyTorch
RUN pip install onnx==1.9.0 ninja
RUN pip install torch==${TORCH_VERSION} torchvision==${TORCHVISION_VERSION} -f https://download.pytorch.org/whl/cu116

# ORT Module
RUN pip install --pre onnxruntime-training -f https://download.onnxruntime.ai/onnxruntime_nightly_cu116.html

RUN pip install torch-ort
RUN python -m torch_ort.configure

WORKDIR /workspace
